# -*- coding: utf-8 -*-
"""Cricket_Performance_Analyst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbXqDV8QGOnmWYYTQmAXUqXBytW-fnhN
"""

!pip install ultralytics supervision

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

print("YOLO Loaded Successfully")

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir())

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.predict(
    source="/content",
    save=True,
    conf=0.3
)

from IPython.display import Video

Video("/content/runs/detect/predict/videoplayback (2).mp4", embed=True)

import os

for root, dirs, files in os.walk("/content/runs/detect/predict"):
    for file in files:
        print(file)

from IPython.display import Video

Video("/content/runs/detect/predict/videoplayback (2).mp4", embed=True)

from IPython.display import Video

Video("/content/runs/detect/predict/videoplayback (2).avi", embed=True)

from IPython.display import Video

Video("output.mp4", embed=True)

import os

file_path = "/content/runs/detect/predict/videoplayback (2).avi"

print("Exists:", os.path.exists(file_path))
print("Size:", os.path.getsize(file_path) if os.path.exists(file_path) else "Not Found")

!ffmpeg -i "/content/runs/detect/predict/videoplayback (2).avi" -vcodec libx264 output.mp4 -y

!ls -lh output.mp4

from IPython.display import HTML
from base64 import b64encode

mp4 = open('output.mp4','rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=800 controls>
      <source src="{data_url}" type="video/mp4">
</video>
""")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/videoplayback (2).mp4",
    tracker="bytetrack.yaml",
    save=True,
    persist=True,
    conf=0.3
)

import os

for root, dirs, files in os.walk("/content/runs/detect/track"):
    for file in files:
        print(file)

!ffmpeg -i "/content/runs/detect/track/videoplayback (2).avi" tracked_output.mp4 -y

!ls -lh tracked_output.mp4

from IPython.display import HTML
from base64 import b64encode

mp4 = open('tracked_output.mp4','rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=800 controls>
      <source src="{data_url}" type="video/mp4">
</video>
""")

from ultralytics import YOLO
import pandas as pd

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/videoplayback (2).mp4",
    tracker="bytetrack.yaml",
    persist=True,
    stream=True
)

tracking_data = []

for frame_num, result in enumerate(results):

    if result.boxes.id is not None:

        boxes = result.boxes.xyxy.cpu().numpy()
        ids = result.boxes.id.cpu().numpy()

        for box, track_id in zip(boxes, ids):

            x1, y1, x2, y2 = box

            center_x = (x1 + x2) / 2
            center_y = (y1 + y2) / 2

            tracking_data.append([
                frame_num,
                int(track_id),
                center_x,
                center_y
            ])

df = pd.DataFrame(
    tracking_data,
    columns=["frame","player_id","x","y"]
)

df.to_csv("player_tracking.csv", index=False)

print(df.head())
print("CSV Saved")

import pandas as pd
import numpy as np

df = pd.read_csv("player_tracking.csv")

distance_data = []

for player_id in df['player_id'].unique():

    player = df[df['player_id'] == player_id]

    total_distance = 0

    for i in range(1, len(player)):

        x1 = player.iloc[i-1]['x']
        y1 = player.iloc[i-1]['y']

        x2 = player.iloc[i]['x']
        y2 = player.iloc[i]['y']

        distance = np.sqrt((x2-x1)**2 + (y2-y1)**2)

        total_distance += distance

    distance_data.append([player_id, total_distance])

distance_df = pd.DataFrame(
    distance_data,
    columns=["player_id","distance_pixels"]
)

distance_df = distance_df.sort_values(
    by="distance_pixels",
    ascending=False
)

print(distance_df)

distance_df.to_csv("player_distance.csv", index=False)

print("Distance CSV Saved")

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("player_tracking.csv")

plt.figure(figsize=(10,6))

plt.hist2d(
    df["x"],
    df["y"],
    bins=50
)

plt.colorbar(label="Player Presence")

plt.title("Field Coverage Heatmap")
plt.xlabel("X Position")
plt.ylabel("Y Position")

plt.savefig("field_heatmap.png")

plt.show()

print("Heatmap Saved")

import pandas as pd
import numpy as np

df = pd.read_csv("player_tracking.csv")

fps = 30  # Adjust if your video has a different FPS

speed_data = []

for player_id in df['player_id'].unique():

    player = df[df['player_id'] == player_id]

    total_distance = 0

    for i in range(1, len(player)):

        x1 = player.iloc[i-1]['x']
        y1 = player.iloc[i-1]['y']

        x2 = player.iloc[i]['x']
        y2 = player.iloc[i]['y']

        distance = np.sqrt((x2-x1)**2 + (y2-y1)**2)

        total_distance += distance

    total_time = len(player) / fps

    avg_speed = total_distance / total_time if total_time > 0 else 0

    speed_data.append([
        player_id,
        total_distance,
        avg_speed
    ])

speed_df = pd.DataFrame(
    speed_data,
    columns=[
        "player_id",
        "distance_pixels",
        "avg_speed_pixels_per_sec"
    ]
)

speed_df = speed_df.sort_values(
    by="avg_speed_pixels_per_sec",
    ascending=False
)

print(speed_df)

speed_df.to_csv("player_speed.csv", index=False)

print("Player Speed CSV Saved")

import pandas as pd

distance_df = pd.read_csv("player_distance.csv")
speed_df = pd.read_csv("player_speed.csv")

final_report = pd.merge(
    distance_df,
    speed_df[["player_id","avg_speed_pixels_per_sec"]],
    on="player_id"
)

final_report.columns = [
    "player_id",
    "distance_pixels",
    "avg_speed_pixels_per_sec"
]

final_report = final_report.sort_values(
    by="distance_pixels",
    ascending=False
)

print(final_report)

final_report.to_csv(
    "cricket_analytics_report.csv",
    index=False
)

print("Final Analytics Report Saved")

import os

for file in os.listdir():
    print(file)

import pandas as pd
import matplotlib.pyplot as plt

speed_df = pd.read_csv("player_speed.csv")

top_players = speed_df.head(10)

plt.figure(figsize=(10,5))
plt.bar(top_players["player_id"].astype(str),
        top_players["avg_speed_pixels_per_sec"])

plt.title("Top Active Players")
plt.xlabel("Player ID")
plt.ylabel("Average Speed")

plt.savefig("top_players_speed.png")

plt.show()

print("Chart Saved")

import pandas as pd

distance_df = pd.read_csv("player_distance.csv")
speed_df = pd.read_csv("player_speed.csv")

dashboard_df = pd.merge(
    distance_df,
    speed_df[["player_id", "avg_speed_pixels_per_sec"]],
    on="player_id"
)

dashboard_df["rank"] = dashboard_df["distance_pixels"].rank(
    ascending=False,
    method="dense"
)

dashboard_df = dashboard_df.sort_values(
    by="distance_pixels",
    ascending=False
)

dashboard_df.to_csv("dashboard_data.csv", index=False)

print(dashboard_df.head())
print("Dashboard Data Saved")

from google.colab import files

files.download("cricket_analytics_report.csv")
files.download("player_tracking.csv")
files.download("player_distance.csv")
files.download("player_speed.csv")
files.download("dashboard_data.csv")
files.download("field_heatmap.png")
files.download("top_players_speed.png")
files.download("tracked_output.mp4")

from google.colab import files

uploaded = files.upload()

import os
print(os.listdir())

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/klvideo1.mp4",
    tracker="bytetrack.yaml",
    save=True,
    persist=True,
    conf=0.3
)

import os

for root, dirs, files in os.walk("/content/runs/detect"):
    for file in files:
        print(root, file)

!find /content/runs -type f | grep -E "\.(avi|mp4)$"

from IPython.display import HTML
from base64 import b64encode

video_path = "/content/klvideo1.mp4"

mp4 = open(video_path,'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=800 controls>
      <source src="{data_url}" type="video/mp4">
</video>
""")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.predict(
    source="/content/klvideo1.mp4",
    save=True,
    conf=0.15
)

!find /content/runs/detect/predict-2 -type f

from IPython.display import HTML
from base64 import b64encode

video_path = "/content/runs/detect/predict-2/klvideo1.mp4"

mp4 = open(video_path,'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=800 controls>
      <source src="{data_url}" type="video/mp4">
</video>
""")

!ffmpeg -i "/content/runs/detect/predict-2/klvideo1.avi" ball_detection.mp4 -y

from IPython.display import HTML
from base64 import b64encode

mp4 = open('ball_detection.mp4','rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=800 controls>
      <source src="{data_url}" type="video/mp4">
</video>
""")

!pip install roboflow

from roboflow import Roboflow

rf = Roboflow(api_key="f3VSKKdRzccFN7EHy5m9")

project = rf.workspace("kika12").project("cricket-ball-6gtio")

version = project.version(1)

dataset = version.download("yolov8")

import os

print(os.listdir())

!ls Cricket-ball-1

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.train(
    data="/content/Cricket-ball-1/data.yaml",
    epochs=30,
    imgsz=640,
    batch=16,
    name="cricket_ball_detector"
)

!find /content/runs -name "best.pt"

from ultralytics import YOLO

model = YOLO("/content/runs/detect/cricket_ball_detector/weights/best.pt")

results = model.predict(
    source="/content/klvideo1.mp4",
    save=True,
    conf=0.25
)

!find /content/runs/detect -type f | grep -E "\.(avi|mp4)$"

!ffmpeg -i "/content/runs/detect/predict3/klvideo1.avi" cricket_ball_output.mp4 -y

from IPython.display import HTML
from base64 import b64encode

mp4 = open('cricket_ball_output.mp4','rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=800 controls>
      <source src="{data_url}" type="video/mp4">
</video>
""")

!find /content/runs/detect -type f | grep -E "\.(avi|mp4)$"

!ffmpeg -i "/content/runs/detect/predict-3/klvideo1.avi" cricket_ball_output.mp4 -y

!ls -lh cricket_ball_output.mp4

from IPython.display import Video

Video("cricket_ball_output.mp4", embed=True)

import os
from PIL import Image
import matplotlib.pyplot as plt

train_images = "/content/Cricket-ball-1/train/images"

images = os.listdir(train_images)[:9]

plt.figure(figsize=(10,10))

for i, img_name in enumerate(images):
    img = Image.open(os.path.join(train_images, img_name))

    plt.subplot(3,3,i+1)
    plt.imshow(img)
    plt.axis("off")

plt.show()

import cv2
import os

video = cv2.VideoCapture("/content/klvideo1.mp4")

os.makedirs("ball_frames", exist_ok=True)

count = 0
saved = 0

while True:
    ret, frame = video.read()

    if not ret:
        break

    if count % 15 == 0:
        cv2.imwrite(f"ball_frames/frame_{saved}.jpg", frame)
        saved += 1

    count += 1

video.release()

print("Frames extracted:", saved)

import cv2
import os

video = cv2.VideoCapture("/content/klvideo1.mp4")

os.makedirs("ball_frames_more", exist_ok=True)

count = 0
saved = 0

while True:
    ret, frame = video.read()

    if not ret:
        break

    if count % 5 == 0:  # instead of 15
        cv2.imwrite(f"ball_frames_more/frame_{saved}.jpg", frame)
        saved += 1

    count += 1

video.release()

print("Frames extracted:", saved)

!zip -r ball_frames_more.zip ball_frames_more

from google.colab import files
files.download("ball_frames_more.zip")

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir())

import cv2
import os

video = cv2.VideoCapture("/content/YOUR_VIDEO_NAME.mp4")

os.makedirs("ball_frames", exist_ok=True)

count = 0
saved = 0

while True:
    ret, frame = video.read()

    if not ret:
        break

    if count % 5 == 0:
        cv2.imwrite(f"ball_frames/frame_{saved}.jpg", frame)
        saved += 1

    count += 1

video.release()

print("Frames extracted:", saved)

import os
from PIL import Image
import matplotlib.pyplot as plt

images = os.listdir("ball_frames")[:9]

plt.figure(figsize=(10,10))

for i, img_name in enumerate(images):
    img = Image.open(os.path.join("ball_frames", img_name))

    plt.subplot(3,3,i+1)
    plt.imshow(img)
    plt.axis("off")

plt.show()

video = cv2.VideoCapture("/content/klmix1.mp4")

import cv2

video = cv2.VideoCapture("/content/klmix1.mp4")

print("Opened:", video.isOpened())

print(os.listdir("/content"))

import cv2
import os

video = cv2.VideoCapture("/content/klmix1.MP4")

os.makedirs("ball_frames", exist_ok=True)

count = 0
saved = 0

while True:
    ret, frame = video.read()

    if not ret:
        break

    if count % 5 == 0:
        cv2.imwrite(f"ball_frames/frame_{saved}.jpg", frame)
        saved += 1

    count += 1

video.release()

print("Frames extracted:", saved)

!rm -rf ball_frames

import os
from PIL import Image
import matplotlib.pyplot as plt

images = os.listdir("ball_frames")[:9]

plt.figure(figsize=(10,10))

for i, img_name in enumerate(images):
    img = Image.open(os.path.join("ball_frames", img_name))

    plt.subplot(3,3,i+1)
    plt.imshow(img)
    plt.axis("off")

plt.show()

import os

for item in os.listdir("/content"):
    print(item)

import cv2
import os

video = cv2.VideoCapture("/content/klmix1.MP4")

print("Opened:", video.isOpened())

count = 0
while True:
    ret, frame = video.read()

    if not ret:
        break

    count += 1

video.release()

print("Total Frames:", count)

import cv2
import os

os.makedirs("ball_frames", exist_ok=True)

video = cv2.VideoCapture("/content/klmix1.MP4")

count = 0
saved = 0

while True:
    ret, frame = video.read()

    if not ret:
        break

    if count % 5 == 0:
        cv2.imwrite(f"ball_frames/frame_{saved}.jpg", frame)
        saved += 1

    count += 1

video.release()

print("Frames extracted:", saved)
print("Folder exists:", os.path.exists("ball_frames"))

import os
from PIL import Image
import matplotlib.pyplot as plt

images = sorted(os.listdir("ball_frames"))[:9]

plt.figure(figsize=(12,12))

for i, img_name in enumerate(images):
    img = Image.open(os.path.join("ball_frames", img_name))

    plt.subplot(3,3,i+1)
    plt.imshow(img)
    plt.axis("off")

plt.tight_layout()
plt.show()

import os
from PIL import Image
import matplotlib.pyplot as plt

images = sorted(os.listdir("ball_frames"))

for start in [0, 50, 100, 150, 200, 250, 300, 350]:

    plt.figure(figsize=(12,4))

    for i in range(6):

        idx = start + i

        if idx >= len(images):
            break

        img = Image.open(
            os.path.join(
                "ball_frames",
                images[idx]
            )
        )

        plt.subplot(1,6,i+1)
        plt.imshow(img)
        plt.axis("off")
        plt.title(idx)

    plt.show()

import os
from PIL import Image
import matplotlib.pyplot as plt

images = sorted(os.listdir("ball_frames"))

# Show frames every 25 images
for start in range(0, min(len(images), 400), 25):

    plt.figure(figsize=(15,3))

    for i in range(5):
        idx = start + i

        if idx >= len(images):
            break

        img = Image.open(
            os.path.join("ball_frames", images[idx])
        )

        plt.subplot(1,5,i+1)
        plt.imshow(img)
        plt.axis("off")
        plt.title(f"Frame {idx}")

    plt.show()

import cv2
import os

video_path = "/content/klmix1.MP4"

cap = cv2.VideoCapture(video_path)

os.makedirs("all_frames", exist_ok=True)

frame_count = 0

while True:
    ret, frame = cap.read()

    if not ret:
        break

    cv2.imwrite(
        f"all_frames/frame_{frame_count:05d}.jpg",
        frame
    )

    frame_count += 1

cap.release()

print("Total Frames Extracted:", frame_count)

!zip -r all_frames.zip all_frames

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir("/content"))

import cv2

video = cv2.VideoCapture("/content/klnewvideo.mp4")

print("Opened:", video.isOpened())

total_frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
fps = video.get(cv2.CAP_PROP_FPS)

print("Total Frames:", total_frames)
print("FPS:", fps)

video.release()

import cv2

video = cv2.VideoCapture("/content/klnewvideo.MP4")

print("Opened:", video.isOpened())

total_frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
fps = video.get(cv2.CAP_PROP_FPS)

print("Total Frames:", total_frames)
print("FPS:", fps)

video.release()

import cv2
import os

os.makedirs("new_ball_frames", exist_ok=True)

video = cv2.VideoCapture("/content/klnewvideo.MP4")

count = 0
saved = 0

while True:
    ret, frame = video.read()

    if not ret:
        break

    cv2.imwrite(f"new_ball_frames/frame_{saved:04d}.jpg", frame)
    saved += 1

video.release()

print("Frames extracted:", saved)

import os
from PIL import Image
import matplotlib.pyplot as plt
import random

images = sorted(os.listdir("new_ball_frames"))

sample = random.sample(images, 9)

plt.figure(figsize=(12,12))

for i, img_name in enumerate(sample):
    img = Image.open(os.path.join("new_ball_frames", img_name))

    plt.subplot(3,3,i+1)
    plt.imshow(img)
    plt.axis("off")

plt.tight_layout()
plt.show()

import cv2
import os

os.makedirs("training_frames", exist_ok=True)

video = cv2.VideoCapture("/content/klnewvideo.MP4")

count = 0
saved = 0

while True:
    ret, frame = video.read()

    if not ret:
        break

    if count % 15 == 0:   # save every 15th frame
        cv2.imwrite(
            f"training_frames/frame_{saved:04d}.jpg",
            frame
        )
        saved += 1

    count += 1

video.release()

print("Frames saved:", saved)

!zip -r training_frames.zip training_frames

from google.colab import files
files.download("training_frames.zip")

import os

for file in os.listdir():
    print(file)

from google.colab import files

uploaded = files.upload()

import os
print(os.listdir("/content"))

!pip install ultralytics

from ultralytics import YOLO

print("YOLO Installed Successfully")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/klnewvideo.MP4",
    tracker="bytetrack.yaml",
    save=True,
    persist=True,
    conf=0.3
)

!find /content/runs/detect/track -type f

!ffmpeg -i "/content/runs/detect/track/klnewvideo.avi" tracked_output.mp4 -y

!ls -lh tracked_output.mp4

!ls -lh tracked_output.mp4

from IPython.display import HTML
from base64 import b64encode

mp4 = open('tracked_output.mp4','rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=800 controls>
      <source src="{data_url}" type="video/mp4">
</video>
""")

from ultralytics import YOLO
import pandas as pd

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/klnewvideo.MP4",
    tracker="bytetrack.yaml",
    persist=True
)

tracking_data = []

for frame_num, result in enumerate(results):

    if result.boxes.id is not None:

        boxes = result.boxes.xyxy.cpu().numpy()
        ids = result.boxes.id.cpu().numpy()

        for box, track_id in zip(boxes, ids):

            x1, y1, x2, y2 = box

            cx = (x1 + x2) / 2
            cy = (y1 + y2) / 2

            tracking_data.append(
                [frame_num, int(track_id), cx, cy]
            )

df = pd.DataFrame(
    tracking_data,
    columns=["Frame","Player_ID","X","Y"]
)

df.to_csv("player_tracking.csv", index=False)

print("CSV Saved")

import pandas as pd
import numpy as np

df = pd.read_csv("player_tracking.csv")

distance_data = []

for player_id in df["Player_ID"].unique():

    player = df[df["Player_ID"] == player_id]

    total_distance = 0

    for i in range(1, len(player)):

        x1, y1 = player.iloc[i-1][["X","Y"]]
        x2, y2 = player.iloc[i][["X","Y"]]

        dist = np.sqrt((x2-x1)**2 + (y2-y1)**2)

        total_distance += dist

    distance_data.append(
        [player_id, total_distance]
    )

distance_df = pd.DataFrame(
    distance_data,
    columns=["Player_ID","Distance"]
)

distance_df.to_csv(
    "player_distance.csv",
    index=False
)

print("Distance CSV Saved")

import pandas as pd
import numpy as np

df = pd.read_csv("player_tracking.csv")

speed_data = []

for player_id in df["Player_ID"].unique():

    player = df[df["Player_ID"] == player_id]

    for i in range(1, len(player)):

        x1, y1 = player.iloc[i-1][["X","Y"]]
        x2, y2 = player.iloc[i][["X","Y"]]

        speed = np.sqrt((x2-x1)**2 + (y2-y1)**2)

        speed_data.append(
            [player_id, player.iloc[i]["Frame"], speed]
        )

speed_df = pd.DataFrame(
    speed_data,
    columns=["Player_ID","Frame","Speed"]
)

speed_df.to_csv(
    "player_speed.csv",
    index=False
)

print("Player Speed CSV Saved")

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("player_tracking.csv")

plt.figure(figsize=(10,6))

plt.hist2d(
    df["X"],
    df["Y"],
    bins=50
)

plt.colorbar(label="Player Presence")

plt.title("Field Activity Heatmap")
plt.xlabel("X Position")
plt.ylabel("Y Position")

plt.savefig(
    "field_heatmap.png",
    bbox_inches="tight"
)

plt.show()

print("Heatmap Saved")

from PIL import Image
from IPython.display import display

display(Image.open("field_heatmap.png"))

import pandas as pd

distance_df = pd.read_csv("player_distance.csv")
speed_df = pd.read_csv("player_speed.csv")

avg_speed = speed_df.groupby("Player_ID")["Speed"].mean().reset_index()
avg_speed.columns = ["Player_ID", "Average_Speed"]

report = distance_df.merge(
    avg_speed,
    on="Player_ID",
    how="left"
)

report.to_csv(
    "cricket_analytics_report.csv",
    index=False
)

print("Final Analytics Report Saved")
print(report.head())

from google.colab import files

files.download("tracked_output.mp4")
files.download("field_heatmap.png")
files.download("player_tracking.csv")
files.download("player_distance.csv")
files.download("player_speed.csv")
files.download("cricket_analytics_report.csv")

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir("/content"))

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/submangill.mp4",
    tracker="bytetrack.yaml",
    save=True,
    persist=True,
    conf=0.3
)

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/submangill.mp4",
    tracker="bytetrack.yaml",
    save=True,
    persist=True,
    conf=0.4,
    imgsz=480
)

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/submangill.mp4",
    tracker="bytetrack.yaml",
    save=True,
    persist=True,
    conf=0.5,
    imgsz=320,
    classes=[0],  # persons only
    vid_stride=3
)

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir("/content"))

print(os.listdir("/clideo_editor_191b670c203b4e50b4f9698e124a9f52.mp4"))

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/clideo_editor_191b670c203b4e50b4f9698e124a9f52.mp4",
    tracker="bytetrack.yaml",
    save=True,
    persist=True,
    conf=0.4,
    classes=[0]   # persons only
)

!pip install ultralytics

from ultralytics import YOLO

print("YOLO Installed Successfully")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/clideo_editor_191b670c203b4e50b4f9698e124a9f52.mp4",
    tracker="bytetrack.yaml",
    save=True,
    persist=True,
    conf=0.4,
    classes=[0],
    imgsz=320,
    vid_stride=3
)

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/clideo_editor_191b670c203b4e50b4f9698e124a9f52.mp4",
    tracker="bytetrack.yaml",
    save=True,
    persist=True,
    conf=0.4,
    classes=[0],
    imgsz=320,
    vid_stride=3
)

!find /content/runs/detect/track-2 -type f

!ffmpeg -i "/content/runs/detect/track-2/clideo_editor_191b670c203b4e50b4f9698e124a9f52.avi" tracked_output.mp4 -y

from IPython.display import HTML
from base64 import b64encode

mp4 = open("tracked_output.mp4", "rb").read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=800 controls>
    <source src="{data_url}" type="video/mp4">
</video>
""")

import cv2

video = cv2.VideoCapture("/content/tracked_output.mp4")

ret, frame = video.read()

cv2.imwrite("sample_frame.jpg", frame)

video.release()

print("Frame Saved")

from PIL import Image
from IPython.display import display

display(Image.open("sample_frame.jpg"))

from PIL import Image
from IPython.display import display

display(Image.open("sample_frame.jpg"))

from PIL import Image
from IPython.display import display

display(Image.open("sample_frame.jpg"))

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir("/content"))

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/0603.mp4",
    tracker="bytetrack.yaml",
    save=True,
    persist=True,
    conf=0.4,
    classes=[0],      # persons only
    imgsz=320,        # faster
    vid_stride=3      # process every 3rd frame
)

!find /content/runs/detect -name "*.avi"

!find /content/runs/detect -type f

!ffmpeg -i "/content/runs/detect/track-3/0603.avi" tracked_0603.mp4 -y

from IPython.display import HTML
from base64 import b64encode

mp4 = open("tracked_0603.mp4", "rb").read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=800 controls>
    <source src="{data_url}" type="video/mp4">
</video>
""")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/0603.mp4",
    tracker="bytetrack.yaml",
    save=True,
    persist=True,
    conf=0.4,
    classes=[0],
    imgsz=320,
    vid_stride=1
)

import pandas as pd
import numpy as np

df = pd.read_csv("player_tracking_0603.csv")

distance_data = []

for player_id in df["Player_ID"].unique():

    player = df[df["Player_ID"] == player_id]

    total_distance = 0

    for i in range(1, len(player)):

        x1, y1 = player.iloc[i-1][["X","Y"]]
        x2, y2 = player.iloc[i][["X","Y"]]

        dist = np.sqrt((x2-x1)**2 + (y2-y1)**2)

        total_distance += dist

    distance_data.append(
        [player_id, total_distance]
    )

distance_df = pd.DataFrame(
    distance_data,
    columns=["Player_ID","Distance"]
)

distance_df.to_csv(
    "player_distance_0603.csv",
    index=False
)

print(distance_df.head())
print("Distance Analysis Completed")

from IPython.display import HTML
from base64 import b64encode

mp4 = open("tracked_0603.mp4", "rb").read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=900 controls>
    <source src="{data_url}" type="video/mp4">
</video>
""")

vid_stride=3

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.track(
    source="/content/0603.mp4",
    tracker="bytetrack.yaml",
    save=True,
    persist=True,
    conf=0.4,
    classes=[0],
    imgsz=320,
    vid_stride=1
)

!find /content/runs/detect/track-5 -name "*.avi"

!ffmpeg -i "/content/runs/detect/track-5/0603.avi" tracked_0603_normal.mp4 -y

from IPython.display import HTML
from base64 import b64encode

mp4 = open("tracked_0603_normal.mp4", "rb").read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=900 controls>
    <source src="{data_url}" type="video/mp4">
</video>
""")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.predict(
    source="/content/0603.mp4",
    save=True,
    conf=0.2
)

!find /content/runs/detect -type f

!ffmpeg -i "/content/runs/detect/predict/0603.avi" detect_0603.mp4 -y

from IPython.display import HTML
from base64 import b64encode

mp4 = open("detect_0603.mp4", "rb").read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=900 controls>
    <source src="{data_url}" type="video/mp4">
</video>
""")

import cv2
import os

video = cv2.VideoCapture("/content/0603.mp4")

os.makedirs("cricket_dataset_frames", exist_ok=True)

count = 0
saved = 0

while True:
    ret, frame = video.read()

    if not ret:
        break

    if count % 5 == 0:
        cv2.imwrite(
            f"cricket_dataset_frames/frame_{saved:04d}.jpg",
            frame
        )
        saved += 1

    count += 1

video.release()

print("Frames Saved:", saved)

import os

print("Total Images:",
      len(os.listdir("cricket_dataset_frames")))

from google.colab import files

files.download("cricket_dataset_frames.zip")

import os

print(os.path.exists("cricket_dataset_frames"))

print(len(os.listdir("cricket_dataset_frames")))

!zip -r cricket_dataset_frames.zip cricket_dataset_frames

from google.colab import files

files.download("cricket_dataset_frames.zip")

!pip install roboflow ultralytics

from roboflow import Roboflow

rf = Roboflow(api_key="rf_Ip9FSyfQLJTNUuvOhPBwL0CylQH2")
project = rf.workspace("shanvitha").project("cricket-object-detection")
dataset = project.version(2).download("yolov11")

!pip install -q roboflow ultralytics

from roboflow import Roboflow

rf = Roboflow(api_key="MRRsHJxUz6Qc3XFtQJkw")

project = rf.workspace("shanvitha").project("cricket-object-detection")

# Version 2 from your screenshot
dataset = project.version(2).download("yolov8")

from roboflow import Roboflow

rf = Roboflow(api_key="MRRsHJxUz6Qc3XFtQJkw")

project = rf.workspace("shanvitha").project("cricket-object-detection")

print(project)

print(project.versions())

print(project)
print(project.id)

from roboflow import Roboflow

rf = Roboflow(api_key="MRRsHJxUz6Qc3XFtQJkw")

print(rf.workspace("shanvitha").projects())

!pip install -q roboflow ultralytics

from roboflow import Roboflow

rf = Roboflow(api_key="MRRsHJxUz6Qc3XFtQJkw")

project = rf.workspace("shanvitha").project("cricekt-object-detection")

print(project.versions())

for v in project.versions():
    print(v.version)

dataset = project.version(2).download("yolov8")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/cricekt-object-detection-2/data.yaml",
    epochs=50,
    imgsz=640
)

from google.colab import files
files.download('/content/runs/detect/train/weights/best.pt')

from ultralytics import YOLO

model = YOLO('/content/runs/detect/train/weights/best.pt')

results = model.predict(
    source='/content/test.jpg',
    conf=0.25,
    save=True
)

from ultralytics import YOLO

model = YOLO('/content/runs/detect/train/weights/best.pt')

results = model.predict(
    source='/content/0603.mp4',
    conf=0.25,
    save=True
)

import os
print(os.listdir('/content'))

!find /content -name best.pt

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir('/content'))

from ultralytics import YOLO

model = YOLO('/content/runs/detect/train/weights/best.pt')

model.predict(
    source='/content/0603.mp4',
    save=True,
    conf=0.25
)

from ultralytics import YOLO

model = YOLO('/content/runs/detect/train/weights/best.pt')

model.predict(
    source='/content/0603.mp4',
    save=True,
    conf=0.25
)

!find /content/runs/detect -type f

!find /content/runs/detect -type f

from IPython.display import Video

Video("/content/runs/detect/predict-3/0603.avi", embed=True)

!ffmpeg -i /content/runs/detect/predict-3/0603.avi /content/output.mp4

from IPython.display import Video

Video("/content/output.mp4", embed=True)

from google.colab import files
files.download('/content/output.mp4')

from ultralytics import YOLO

model = YOLO('/content/runs/detect/train/weights/best.pt')

model.predict(
    source='/content/new_video.mp4',
    save=True,
    conf=0.25
)

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir('/content'))

from ultralytics import YOLO

model = YOLO('/content/runs/detect/train/weights/best.pt')

results = model.predict(
    source='/content/klvideo1.mp4',
    save=True,
    conf=0.25
)

!find /content/runs/detect -name "*.mp4"

from IPython.display import Video

Video("/content/runs/detect/predict4/klvideo1.avi", embed=True)

!ffmpeg -i "/content/runs/detect/predict4/klvideo1.avi" "/content/klvideo1_output.mp4"

from IPython.display import Video

Video("/content/klvideo1_output.mp4", embed=True)

!find /content/runs/detect -type f

!ffmpeg -i "/content/runs/detect/predict-4/klvideo1.avi" "/content/klvideo1_output.mp4"

from IPython.display import Video

Video("/content/klvideo1_output.mp4", embed=True)

from ultralytics import YOLO

model = YOLO('/content/runs/detect/train/weights/best.pt')

results = model.track(
    source='/content/0603.mp4',
    tracker='bytetrack.yaml',
    save=True,
    persist=True
)

!find /content/runs/detect/track -type f

!ffmpeg -i "/content/runs/detect/track/0603.avi" "/content/tracked.mp4"

from IPython.display import Video
Video("/content/tracked.mp4", embed=True)

!ffmpeg -y -i "/content/runs/detect/track/0603.avi" "/content/tracked.mp4"

from IPython.display import Video
Video("/content/tracked.mp4", embed=True)

from ultralytics import YOLO

model = YOLO('/content/runs/detect/train/weights/best.pt')

results = model.track(
    source='/content/0603.mp4',
    tracker='bytetrack.yaml',
    persist=True,
    stream=True
)

for r in results:
    if r.boxes.id is not None:
        print(r.boxes.id)
    break

import pandas as pd
import numpy as np

df = pd.read_csv('/content/player_positions.csv')

distance_data = []

for player in df['player_id'].unique():

    player_df = df[df['player_id'] == player]

    total_distance = 0

    for i in range(1, len(player_df)):

        x1 = player_df.iloc[i-1]['x']
        y1 = player_df.iloc[i-1]['y']

        x2 = player_df.iloc[i]['x']
        y2 = player_df.iloc[i]['y']

        distance = np.sqrt(
            (x2-x1)**2 +
            (y2-y1)**2
        )

        total_distance += distance

    distance_data.append([
        player,
        total_distance
    ])

result_df = pd.DataFrame(
    distance_data,
    columns=['player_id','distance_pixels']
)

print(result_df)

!find /content -name "player_positions.csv"

from ultralytics import YOLO

model = YOLO('/content/runs/detect/train/weights/best.pt')

results = model.track(
    source='/content/0603.mp4',
    tracker='bytetrack.yaml',
    persist=True,
    stream=True
)

for r in results:
    print("Frame processed")
    break

import pandas as pd
from ultralytics import YOLO

model = YOLO('/content/runs/detect/train/weights/best.pt')

data = []

results = model.track(
    source='/content/0603.mp4',
    tracker='bytetrack.yaml',
    persist=True,
    stream=True
)

frame_no = 0

for r in results:
    frame_no += 1

    if r.boxes.id is not None:

        ids = r.boxes.id.cpu().numpy()
        boxes = r.boxes.xywh.cpu().numpy()

        for pid, box in zip(ids, boxes):
            x, y, w, h = box

            data.append([
                frame_no,
                int(pid),
                float(x),
                float(y)
            ])

df = pd.DataFrame(
    data,
    columns=['frame', 'player_id', 'x', 'y']
)

print("Rows collected:", len(df))

df.to_csv('/content/player_positions.csv', index=False)

print("CSV saved!")

import os
print(os.path.exists('/content/player_positions.csv'))

print("Rows collected:", len(df))

import os
print(os.path.exists('/content/player_positions.csv'))

import pandas as pd
import numpy as np

df = pd.read_csv('/content/player_positions.csv')

distance_data = []

for player in df['player_id'].unique():

    player_df = df[df['player_id'] == player].sort_values('frame')

    total_distance = 0

    for i in range(1, len(player_df)):

        x1 = player_df.iloc[i-1]['x']
        y1 = player_df.iloc[i-1]['y']

        x2 = player_df.iloc[i]['x']
        y2 = player_df.iloc[i]['y']

        distance = np.sqrt(
            (x2 - x1)**2 +
            (y2 - y1)**2
        )

        total_distance += distance

    distance_data.append([player, total_distance])

result_df = pd.DataFrame(
    distance_data,
    columns=['player_id', 'distance_pixels']
)

result_df = result_df.sort_values(
    by='distance_pixels',
    ascending=False
)

print(result_df)

result_df.to_csv(
    '/content/player_analytics.csv',
    index=False
)

print("Analytics saved!")

print(result_df.head(10))

import pandas as pd

df = pd.read_csv('/content/player_positions.csv')

fps = 30  # your video is 30 FPS

time_data = []

for player in df['player_id'].unique():

    player_df = df[df['player_id'] == player]

    frames_seen = len(player_df)

    time_seconds = frames_seen / fps

    time_data.append([
        player,
        round(time_seconds, 2)
    ])

time_df = pd.DataFrame(
    time_data,
    columns=['player_id', 'time_on_field_sec']
)

print(time_df)

analytics_df = result_df.merge(
    time_df,
    on='player_id'
)

analytics_df['avg_speed_pixels_per_sec'] = (
    analytics_df['distance_pixels'] /
    analytics_df['time_on_field_sec']
)

analytics_df = analytics_df.sort_values(
    by='distance_pixels',
    ascending=False
)

print(analytics_df)

analytics_df.to_csv(
    '/content/final_cricket_analytics.csv',
    index=False
)

print("Final analytics saved!")